// @skervik/core — foundational domain types (M0 skeleton, S0.5.1).
//
// These are the minimal, real shapes behind the engine contract from tech
// spec §4.1 (`reduce`/`validate` themselves land in S0.5.2). Per ADR-0003
// every type here is plain data — no class instances, no functions, no
// `Map`/`Set` — so `GameState` can be event-sourced and deep-compared via
// JSON. M1 Classic rules extend these shapes; this file does not invent a
// full ruleset.

import type { EdgeId, TileId, VertexId } from './board.js';

/** Opaque identifier for a match (room / game instance). */
export type MatchId = string;

/** Opaque identifier for a player within a match. */
export type PlayerId = string;

/**
 * Resource kind held by a player. Left abstract on purpose: the concrete
 * archipelago resource set (timber, ore, fish, ...) is an M1 ruleset
 * decision, not a core-skeleton concern.
 */
export type ResourceType = string;

/** Coarse lifecycle stage of a match. M1 will refine/extend this set. */
export type GamePhase = 'lobby' | 'setup' | 'main' | 'finished';

/**
 * A tile's resource kind, or `'desert'` (produces nothing, hosts the
 * robber's starting position). The concrete Classic set
 * (`timber/clay/fleece/barley/iron`) is generated by `boardgen.ts` (S1.1.2);
 * this alias just names the shape for `GameState`/events.
 */
export type TileKind = ResourceType | 'desert';

/**
 * One port's trade content: generic 3:1 with any resource, or a specific
 * resource's 2:1. Assigned onto the S1.1.1 `BoardTopology.portSlots` by
 * `boardgen.ts` (S1.1.2) — `PortContent[i]` pairs with `portSlots[i]`.
 */
export type PortContent =
  | { readonly kind: 'generic'; readonly rate: 3 }
  | { readonly kind: 'resource'; readonly rate: 2; readonly resource: ResourceType };

/**
 * A single player's public state. Plain data only (ADR-0003): `resources`
 * is a plain object, never a `Map`, so it serializes and deep-compares
 * deterministically.
 */
export interface PlayerState {
  readonly id: PlayerId;
  readonly name: string;
  readonly victoryPoints: number;
  readonly resources: Readonly<Record<ResourceType, number>>;
}

/**
 * The generated board layout (S1.1.2, `boardgen.ts`): tile kinds and number
 * tokens keyed by `TileId` (S1.1.1), port contents parallel to
 * `BoardTopology.portSlots`, and the robber's starting tile. Landed on
 * `GameState` by applying a `board.generated` event — never recomputed by
 * `reduce` itself (ADR-0003: the layout is a fact, not a recipe).
 */
export interface BoardState {
  readonly tileKinds: Readonly<Record<TileId, TileKind>>;
  /** Non-desert tiles only — a desert tile has no key here (not `undefined`). */
  readonly tileTokens: Readonly<Record<TileId, number>>;
  readonly portContents: readonly PortContent[];
  readonly robberTileId: TileId;
}

/**
 * Placed settlements/roads, keyed by board position (S1.1.3). Plain
 * `Record`s, not `Map`s (ADR-0003) — `settlements[vertexId]`/`roads[edgeId]`
 * is the owning player, or absent if that position is unbuilt.
 */
export interface BuildingsState {
  readonly settlements: Readonly<Record<VertexId, PlayerId>>;
  readonly roads: Readonly<Record<EdgeId, PlayerId>>;
}

/**
 * The full authoritative game state. A plain, JSON-serializable object —
 * no class instances, no functions, no `Map`/`Set` — so it can be
 * event-sourced (replay = truth) and deep-compared byte-for-byte
 * (ADR-0003, `docs/wiki/deterministic-core.md`).
 */
export interface GameState {
  readonly matchId: MatchId;
  readonly phase: GamePhase;
  /** 1-based turn counter; advances on `turn.ended`. */
  readonly turn: number;
  readonly currentPlayerId: PlayerId;
  readonly players: ReadonlyArray<PlayerState>;
  /**
   * Count of events applied so far. Doubles as the PRNG stream index
   * (`docs/wiki/fair-rng-commit-reveal.md`): randomness is derived from
   * `seed` + this index, never drawn ambiently.
   */
  readonly eventIndex: number;
  /** `SHA256(seed)`, published before the match (commit step of commit-reveal). */
  readonly seedHash: string;
  /**
   * Present once `board.generated` has been applied (S1.1.2), absent
   * before — optional rather than a placeholder value so pre-S1.1.2 golden
   * fixtures (no board event in their log) stay byte-identical unchanged.
   */
  readonly board?: BoardState;
  /**
   * Present once the first `settlement.placed` has been applied (S1.1.3),
   * absent before — same "fact of an event having landed" optionality as
   * {@link GameState.board}, so fixtures that never reach the setup
   * placement flow stay byte-identical.
   */
  readonly buildings?: BuildingsState;
  /**
   * The vertex of the settlement placed earlier THIS draft turn, awaiting
   * its attached road (S1.1.3 snake draft) — absent when no settlement is
   * pending (either between draft turns, or outside setup entirely). Set by
   * `settlement.placed`, cleared by `road.placed`.
   */
  readonly pendingRoadVertexId?: VertexId;
  /**
   * The finite bank's remaining pool, per resource (S1.2.1 production/bank-
   * exhaustion rule). Absent until the first `resources.produced` event
   * touches a resource — same "fact of an event having landed" optionality
   * as {@link GameState.board}; a resource with no key here still has its
   * full Classic pool (`CLASSIC_PRODUCTION_PROFILE.bankPerResource`,
   * `validate.ts`), it just hasn't been drawn from yet.
   */
  readonly bank?: Readonly<Record<ResourceType, number>>;
}

/** Fields shared by every {@link GameEvent} variant. */
interface BaseGameEvent {
  /** Position of this event in the match's event log / PRNG stream. */
  readonly index: number;
}

/** Emitted once when a match's authoritative state is initialized. */
export interface MatchStartedEvent extends BaseGameEvent {
  readonly type: 'match.started';
  readonly matchId: MatchId;
  readonly seedHash: string;
  readonly playerIds: ReadonlyArray<PlayerId>;
}

/**
 * Emitted once during setup when the Classic board layout is generated from
 * the match seed (S1.1.2, `boardgen.ts`). Carries the FULL layout — tile
 * kinds/tokens, port contents, robber start — so replay never re-runs the
 * generator; the layout is a fact, like every other event (ADR-0003).
 */
export interface BoardGeneratedEvent extends BaseGameEvent {
  readonly type: 'board.generated';
  readonly tileKinds: Readonly<Record<TileId, TileKind>>;
  readonly tileTokens: Readonly<Record<TileId, number>>;
  readonly portContents: readonly PortContent[];
  readonly robberTileId: TileId;
}

/**
 * A dice roll resolved by the server from the seeded PRNG (S1.2.1: Classic
 * play is always 2d6, not 1 die — `dieA`/`dieB`/`total` are facts, never
 * generated inside `reduce` itself, only carried as event data, ADR-0003).
 * Recording both faces (not just `total`) means replay never needs to
 * re-derive them from the seed — see `docs/wiki/rng-stream-map.md`.
 */
export interface DiceRolledEvent extends BaseGameEvent {
  readonly type: 'dice.rolled';
  readonly playerId: PlayerId;
  readonly dieA: number;
  readonly dieB: number;
  readonly total: number;
}

/**
 * Resource production resolved from a roll (S1.2.1 Classic spec): `grants`
 * is the explicit per-player payout (keyed by `PlayerId`, then
 * `ResourceType`) and `bank` is the FULL resultant bank pool after this
 * roll — both are facts `validate` computes once so `reduce`/replay never
 * recompute the bank-exhaustion math (ADR-0003). Emitted alongside
 * `dice.rolled` for every roll except a 7 (robber — deferred to S1.3.1,
 * see the `validate.ts` `rollDice` branch); `grants` is `{}` when nothing
 * produces (e.g. no board yet, no tile matches, or bank exhaustion voided
 * every entitled resource this roll) — still emitted so "this roll produced
 * nothing" is itself a recorded fact, not an absence to infer.
 */
export interface ResourcesProducedEvent extends BaseGameEvent {
  readonly type: 'resources.produced';
  readonly grants: Readonly<Record<PlayerId, Readonly<Record<ResourceType, number>>>>;
  readonly bank: Readonly<Record<ResourceType, number>>;
}

/** Emitted when a player's turn ends and play passes to the next player. */
export interface TurnEndedEvent extends BaseGameEvent {
  readonly type: 'turn.ended';
  readonly playerId: PlayerId;
  readonly nextPlayerId: PlayerId;
}

/**
 * Emitted when a player places a settlement during the snake-draft setup
 * phase (S1.1.3). `payout` is the second-settlement resource grant (tech
 * spec: 1 resource per adjacent producing tile, desert pays nothing) —
 * `validate` computes it once from `GameState.board`, and it travels here as
 * an explicit fact so `reduce`/replay never recompute it (ADR-0003). Empty
 * for a player's first settlement.
 */
export interface SettlementPlacedEvent extends BaseGameEvent {
  readonly type: 'settlement.placed';
  readonly playerId: PlayerId;
  readonly vertexId: VertexId;
  readonly payout: Readonly<Record<ResourceType, number>>;
}

/**
 * Emitted when a player places the road attached to the settlement they
 * just placed, completing one snake-draft turn (S1.1.3). `nextPlayerId`/
 * `nextPhase` are the snake-order/setup-completion facts `validate` already
 * worked out — `reduce` only applies them, never re-derives draft order
 * (ADR-0003: events are facts, not recipes).
 */
export interface RoadPlacedEvent extends BaseGameEvent {
  readonly type: 'road.placed';
  readonly playerId: PlayerId;
  readonly edgeId: EdgeId;
  readonly nextPlayerId: PlayerId;
  readonly nextPhase: GamePhase;
}

/**
 * A fact that mutates {@link GameState} via `reduce`. Discriminated by
 * `type`. Only events change state — intents never do directly
 * (ADR-0003). This is a minimal M0 set; M1 Classic rules add
 * build/trade/robber/etc.
 */
export type GameEvent =
  | MatchStartedEvent
  | BoardGeneratedEvent
  | DiceRolledEvent
  | ResourcesProducedEvent
  | TurnEndedEvent
  | SettlementPlacedEvent
  | RoadPlacedEvent;

/** Fields shared by every {@link PlayerIntent} variant. */
interface BaseIntent {
  readonly playerId: PlayerId;
}

/** A player's request to roll the dice on their turn. */
export interface RollDiceIntent extends BaseIntent {
  readonly type: 'intent.rollDice';
}

/** A player's request to end their turn. */
export interface EndTurnIntent extends BaseIntent {
  readonly type: 'intent.endTurn';
}

/** A player's request to place a settlement on a vertex during the setup draft. */
export interface PlaceSettlementIntent extends BaseIntent {
  readonly type: 'intent.placeSettlement';
  readonly vertexId: VertexId;
}

/**
 * A player's request to place the road attached to the settlement they just
 * placed this draft turn (setup phase only — see {@link GameState.pendingRoadVertexId}).
 */
export interface PlaceRoadIntent extends BaseIntent {
  readonly type: 'intent.placeRoad';
  readonly edgeId: EdgeId;
}

/**
 * A player's wish, sent from the client. Discriminated by `type`. Passed
 * through `validate` (S0.5.2), which turns a legal intent into
 * {@link GameEvent}s or rejects it with a {@link RejectReason} — an intent
 * never mutates state directly (ADR-0003). This is a minimal M0 set; M1
 * Classic rules add build/trade/etc.
 */
export type PlayerIntent =
  RollDiceIntent | EndTurnIntent | PlaceSettlementIntent | PlaceRoadIntent;

/**
 * Why `validate` refused an intent. An enumerated string-literal union so
 * rejections serialize plainly (e.g. over the wire in `intent.rejected`,
 * tech spec §5.3) and can be switched on exhaustively.
 */
export type RejectReason =
  | 'NOT_YOUR_TURN'
  | 'INVALID_PHASE'
  | 'UNKNOWN_PLAYER'
  | 'MALFORMED_INTENT'
  | 'OCCUPIED'
  | 'DISTANCE_VIOLATION'
  | 'DETACHED_ROAD'
  | 'WRONG_PHASE';
